-- TradeOptix Database Schema (Postgres / InsForge)
-- InsForge Dashboard → SQL Editor → paste → Run

-- Signals generated by signal_engine.py
CREATE TABLE IF NOT EXISTS signals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    symbol TEXT NOT NULL,                -- BTCUSDT, ETHUSDT...
    timeframe TEXT NOT NULL DEFAULT '1d',
    direction SMALLINT NOT NULL,         -- 1 = LONG, -1 = SHORT
    entry_price DOUBLE PRECISION NOT NULL,
    stop_loss DOUBLE PRECISION NOT NULL,
    take_profit DOUBLE PRECISION NOT NULL,
    atr DOUBLE PRECISION NOT NULL,
    rr_ratio DOUBLE PRECISION NOT NULL DEFAULT 3.0,
    status TEXT NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE / TP_HIT / SL_HIT / EXPIRED / CANCELLED
    signal_time TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_signals_symbol_time ON signals(symbol, signal_time DESC);
CREATE INDEX IF NOT EXISTS idx_signals_status ON signals(status);

-- Trade tracking (user ne trade liya + SL Guard events)
CREATE TABLE IF NOT EXISTS tracked_trades (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    signal_id UUID REFERENCES signals(id) ON DELETE SET NULL,
    symbol TEXT NOT NULL,
    direction SMALLINT NOT NULL,
    entry_price DOUBLE PRECISION NOT NULL,
    stop_loss DOUBLE PRECISION NOT NULL,
    take_profit DOUBLE PRECISION NOT NULL,
    status TEXT NOT NULL DEFAULT 'OPEN',    -- OPEN / CLOSED / SL_HIT / TP_HIT
    opened_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    closed_at TIMESTAMPTZ,
    pnl_pct DOUBLE PRECISION
);

-- Alert log (SL warnings — SL hit se pehle ki warnings)
CREATE TABLE IF NOT EXISTS alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tracked_trade_id UUID REFERENCES tracked_trades(id) ON DELETE CASCADE,
    symbol TEXT NOT NULL,
    alert_type TEXT NOT NULL,               -- SL_WARNING / SL_HIT / TP_HIT / SIGNAL_NEW
    price_at_alert DOUBLE PRECISION,
    message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_alerts_time ON alerts(created_at DESC);

-- Row Level Security (InsForge/Supabase-style): sab read kar sakte hain, write sirf service key se
ALTER TABLE signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE tracked_trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public read signals" ON signals FOR SELECT USING (true);
CREATE POLICY "public read alerts" ON alerts FOR SELECT USING (true);
CREATE POLICY "public read trades" ON tracked_trades FOR SELECT USING (true);
